### ISSUE TITLE
i want to add a warning regarding health while searching the beer 

### ISSUE THREAD

**Issue by ashfaque-mustaque** [urz-ahmed/beer-store#11]
hey @urz-ahmed i want to add a warning pop up while searching the beer because alchohlilc beer is injurious to health.
would you want to assign me this make this contribution to your repo.

**Comment by urzahmed** [comment]
Good you can do it and make sure while creating PR mention your PR here

**Comment by ashfaque-mustaque** [comment]
brother @urz-ahmed i completed the assignment which you had assigned me try to merge it soon brother.
please have a look I am sharing a screenshot of it
![beer-store1](https://github.com/urz-ahmed/beer-store/assets/106698498/a0f34ff3-45e0-4233-b811-6a815d6ec590)
