### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by urzahmed** [urz-ahmed/beer-store#2]
implement dark mode switch in this website

**Comment by Yash-RajSingh** [comment]
Hey @urz-ahmed ,
I'd like to take up this issue up under hacktoberfest 2023. Can you please assign this issue to me?

**Comment by kiransatdive** [comment]
I want to work this issue, Can you Please assign me .

**Comment by belal-akram** [comment]
I can tackle the Issue you mentioned .Could you please assign this task to me?

**Comment by mdfaizalam555** [comment]
please appoint me , I want to work on this issue.

**Comment by cdelacruzzin** [comment]
It seems that when you change to the "dark mode" state, and click on the links on the navbar, the state resets back to light mode.
Or in general, when you reload the page, the state resets.
I would like to fix this bug
