### ISSUE TITLE
"Refactor `App.js` by Breaking Code into Separate Components"

### ISSUE THREAD

**Issue by cdelacruzzin** [urz-ahmed/beer-store#9]
Import components to App.js, and render those components, instead of writing all the code on App.js. 
for example, 
Design a Homepage component.
Export the Homepage component.
Incorporate the Homepage component into App.js.
Display the integrated Homepage component within App.js."

**Comment by cdelacruzzin** [comment]
I would like to work on this issue

**Comment by urzahmed** [comment]
Ok you can work on this

**Comment by Harishprethiv7** [comment]
I can do it.
Kindly assign it to me.

**Comment by cdelacruzzin** [comment]
Can you assign it to me?
